services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: milkco-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_strong_password123"
    ports:
      - "14333:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P Your_strong_password123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: milkco-api
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=MilkCoPOSDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;MultipleActiveResultSets=true
    ports:
      - "8080:8080"

volumes:
  sql_data:
